# Define pools of pixelmon items to add to loot tables.
rolls:
  min: 2
  max: 5

loot_tables:
  abandoned_mineshaft:
    - poke_ball
    - leaf_stone
    - fire_stone
    - water_stone
    - sun_stone
    - moon_stone
    - rare_candy
  desert_pyramid:
    - poke_ball
    - moon_stone
  end_city_treasure:
    - poke_ball
    - dawn_stone
    - dusk_stone
  igloo_chest:
    - poke_ball
    - water_stone
  jungle_temple:
    - poke_ball
    - leaf_stone
    - sun_stone
  jungle_temple_dispenser:
    - poke_ball
    - rare_candy
  nether_bridge:
    - poke_ball
    - fire_stone
    - rare_candy
  simple_dungeon:
    - poke_ball
    - water_stone
    - dawn_stone
    - dusk_stone
  spawn_bonus_chest:
    - poke_ball
    - rare_candy
  stronghold_corridor:
    - poke_ball
  stronghold_crossing:
    - poke_ball
  stronghold_library:
    - poke_ball
    - dawn_stone
    - dusk_stone
  village_blacksmith:
    - poke_ball
    - leaf_stone
    - fire_stone
    - sun_stone
    - moon_stone
